### ISSUE TITLE
"Can't find end of the entity" when using the Youtube plugin

### ISSUE THREAD

**Issue by koodoxz** [Telegram-Bot-Node/Nikoro#134]
Hi All

I found new issue for youtube plugin

here is the log when i try to find song on youtube with 32 characters including space, ex : **/yt andra and the backbone - hitamku** and also with this one, **/yt asd** it wont work

info: [Bot] Plugins loaded.
info: [Bot] Permissions configured.
info: [Bot] The bot is online!
error: [Bot] Unhandled rejection at Promise Promise {
_bitField: 18087936,
_fulfillmentHandler0:
{ Error: ETELEGRAM: 400 Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 92
at BaseError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:10:5)
at TelegramError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:56:5)
at request.then.err (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/telegram.js:213:15)
at tryCatcher (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:693:18)
at Async._drainQueue (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:143:10)
code: 'ETELEGRAM',
response:
IncomingMessage {
_readableState: [Object],
readable: false,
domain: null,
_events: [Object],
_eventsCount: 4,
_maxListeners: undefined,
socket: [Object],
connection: [Object],
httpVersionMajor: 1,
httpVersionMinor: 1,
httpVersion: '1.1',
complete: true,
headers: [Object],
rawHeaders: [Object],
trailers: {},
rawTrailers: [],
upgrade: false,
url: '',
method: null,
statusCode: 400,
statusMessage: 'Bad Request',
client: [Object],
_consuming: true,
_dumped: false,
req: [Object],
request: [Object],
toJSON: [Function: responseToJSON],
caseless: [Object],
read: [Function],
body: [Object] } },
_rejectionHandler0: undefined,
_promise0: undefined,
_receiver0: undefined,
_cancellationParent:
Promise {
_bitField: 16777216,
_fulfillmentHandler0:
{ Error: ETELEGRAM: 400 Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 92
at BaseError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:10:5)
at TelegramError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:56:5)
at request.then.err (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/telegram.js:213:15)
at tryCatcher (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:693:18)
at Async._drainQueue (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:143:10) code: 'ETELEGRAM', response: [Object] },
_rejectionHandler0: [Function],
_promise0: undefined,
_receiver0: undefined,
_cancellationParent: undefined,
_branchesRemainingToCancel: 1,
_onCancelField: undefined } } with reason Error: ETELEGRAM: 400 Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 92
at BaseError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:10:5)
at TelegramError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:56:5)
at request.then.err (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/telegram.js:213:15)
at tryCatcher (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:693:18)
at Async._drainQueue (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:143:10)

But if i want to search normal song : **/yt alicia kara - stay** and the another songs is no issue

**Comment by CapacitorSet** [comment]
Internal note: as mentioned in [the other issue](https://github.com/crisbal/Telegram-Bot-Node/issues/129#issuecomment-332368886), this might be due to the title of the song containing square brackets that mess with the formatting.

@Ichicoro, want to give it a shot? You should try enabling the YouTube plugin, troubleshoot it (my hypothesis might be a good starting point), and possibly push a fix :)

**Comment by CapacitorSet** [comment]
Thank you for your report, we fixed that and a similar issue in Fap.js.
